# Copyright 2024 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Records a dataset. Actions for the robot can be either generated by teleoperation or by a policy.

Example:

```shell
lerobot-record \
    --robot.type=so100_follower \
    --robot.port=/dev/tty.usbmodem58760431541 \
    --robot.cameras="{laptop: {type: opencv, index_or_path: 0, width: 640, height: 480, fps: 30}}" \
    --robot.id=black \
    --dataset.repo_id=<my_username>/<my_dataset_name> \
    --dataset.num_episodes=2 \
    --dataset.single_task="Grab the cube" \
    --dataset.streaming_encoding=true \
    --dataset.encoder_threads=2 \
    --display_data=true
    # <- Optional: specify video codec (auto, h264, hevc, libsvtav1). Default is libsvtav1. \
    # --dataset.vcodec=h264 \
    # <- Teleop optional if you want to teleoperate to record or in between episodes with a policy \
    # --teleop.type=so100_leader \
    # --teleop.port=/dev/tty.usbmodem58760431551 \
    # --teleop.id=blue \
    # <- Policy optional if you want to record with a policy \
    # --policy.path=${HF_USER}/my_policy \
```

Example recording with bimanual so100:
```shell
lerobot-record \
  --robot.type=bi_so_follower \
  --robot.left_arm_config.port=/dev/tty.usbmodem5A460822851 \
  --robot.right_arm_config.port=/dev/tty.usbmodem5A460814411 \
  --robot.id=bimanual_follower \
  --robot.left_arm_config.cameras='{
    wrist: {"type": "opencv", "index_or_path": 1, "width": 640, "height": 480, "fps": 30},
    top: {"type": "opencv", "index_or_path": 3, "width": 640, "height": 480, "fps": 30},
  }' --robot.right_arm_config.cameras='{
    wrist: {"type": "opencv", "index_or_path": 2, "width": 640, "height": 480, "fps": 30},
    front: {"type": "opencv", "index_or_path": 4, "width": 640, "height": 480, "fps": 30},
  }' \
  --teleop.type=bi_so_leader \
  --teleop.left_arm_config.port=/dev/tty.usbmodem5A460852721 \
  --teleop.right_arm_config.port=/dev/tty.usbmodem5A460819811 \
  --teleop.id=bimanual_leader \
  --display_data=true \
  --dataset.repo_id=${HF_USER}/bimanual-so-handover-cube \
  --dataset.num_episodes=25 \
  --dataset.single_task="Grab and handover the red cube to the other arm" \
  --dataset.streaming_encoding=true \
  # --dataset.vcodec=auto \
  --dataset.encoder_threads=2
```
"""
import os
os.environ["HF_HUB_OFFLINE"] = "1"
os.environ["TRANSFORMERS_OFFLINE"] = "1"
import logging
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path
from pprint import pformat
from typing import Any

from lerobot.cameras import (  # noqa: F401
    CameraConfig,  # noqa: F401
)
from lerobot.cameras.opencv.configuration_opencv import OpenCVCameraConfig  # noqa: F401
from lerobot.cameras.reachy2_camera.configuration_reachy2_camera import Reachy2CameraConfig  # noqa: F401
from lerobot.cameras.realsense.configuration_realsense import RealSenseCameraConfig  # noqa: F401
from lerobot.cameras.zmq.configuration_zmq import ZMQCameraConfig  # noqa: F401
from lerobot.configs import parser
from lerobot.configs.policies import PreTrainedConfig
from lerobot.datasets.image_writer import safe_stop_image_writer
from lerobot.datasets.lerobot_dataset import LeRobotDataset
from lerobot.datasets.pipeline_features import aggregate_pipeline_dataset_features, create_initial_features
from lerobot.datasets.utils import build_dataset_frame, combine_feature_dicts
from lerobot.datasets.video_utils import VideoEncodingManager
from lerobot.policies.factory import make_policy, make_pre_post_processors
from lerobot.policies.pretrained import PreTrainedPolicy
from lerobot.policies.utils import make_robot_action
from lerobot.processor import (
    PolicyAction,
    PolicyProcessorPipeline,
    RobotAction,
    RobotObservation,
    RobotProcessorPipeline,
    make_default_processors,
)
from lerobot.processor.rename_processor import rename_stats
from lerobot.robots import (  # noqa: F401
    Robot,
    RobotConfig,
    bi_openarm_follower,
    bi_so_follower,
    earthrover_mini_plus,
    hope_jr,
    koch_follower,
    make_robot_from_config,
    omx_follower,
    openarm_follower,
    reachy2,
    so_follower,
    unitree_g1 as unitree_g1_robot,
)
from lerobot.teleoperators import (  # noqa: F401
    Teleoperator,
    TeleoperatorConfig,
    bi_openarm_leader,
    bi_so_leader,
    homunculus,
    koch_leader,
    make_teleoperator_from_config,
    omx_leader,
    openarm_leader,
    openarm_mini,
    reachy2_teleoperator,
    so_leader,
    unitree_g1,
)
from lerobot.teleoperators.keyboard.teleop_keyboard import KeyboardTeleop
from lerobot.utils.constants import ACTION, OBS_STR
from lerobot.utils.control_utils import (
    init_keyboard_listener,
    is_headless,
    predict_action,
    sanity_check_dataset_name,
    sanity_check_dataset_robot_compatibility,
)
from lerobot.utils.import_utils import register_third_party_plugins
from lerobot.utils.robot_utils import precise_sleep
from lerobot.utils.utils import (
    get_safe_torch_device,
    init_logging,
    log_say,
)
from lerobot.utils.visualization_utils import init_rerun, log_rerun_data

# 🔴 추가: import
import numpy as np
import torch
import torch.nn as nn
import sys
import os
import re
import signal
from PIL import Image
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
from lerobot.scripts.yolo_detect import detect_object, detected_to_obs
from lerobot.scripts.gym_env import DeskCleanEnv
from lerobot.scripts.RL_deploy import decide_action, update_bin_weights
from lerobot.scripts.tts import play_tts

LEROBOT_REPO_ROOT = Path(os.environ.get("LEROBOT_REPO_ROOT", Path(BASE_DIR).parent))
MODEL_POLICIES_DIR = Path(
    os.environ.get(
        "LEROBOT_MODEL_POLICIES_DIR",
        LEROBOT_REPO_ROOT / "src" / "lerobot" / "model_policies",
    )
)

# 🔴 추가: 사용할 전역변수
# current bin state
bin_weights = {
    "first_drawer": 0.0,
    "second_drawer": 0.0,
    "gray_bin": 0.0,
    "white_bin": 0.0,
}

STOP_REQUESTED = False
CURRENT_EVENTS = None


def request_stop_from_signal(signum, _frame) -> None:
    global STOP_REQUESTED
    STOP_REQUESTED = True
    if CURRENT_EVENTS is not None:
        CURRENT_EVENTS["stop_recording"] = True
        CURRENT_EVENTS["exit_early"] = True
    print("\nWEB_STATUS:모드를 종료합니다.", flush=True)


signal.signal(signal.SIGINT, request_stop_from_signal)
signal.signal(signal.SIGTERM, request_stop_from_signal)


def web_status(message: str) -> None:
    print(f"WEB_STATUS:{message}", flush=True)


def web_running() -> None:
    print("WEB_RUNNING", flush=True)


OBJECT_KO_MAP = {
    "Battery": "배터리",
    "Cup": "컵",
    "Screwdriver": "드라이버",
    "Tape": "테이프",
}

TARGET_KO_MAP = {
    "gray_bin": "공구상자",
    "white_bin": "바구니",
    "first_drawer": "첫 번째 서랍",
    "second_drawer": "두 번째 서랍",
}


def task_to_korean_cleanup_message(task: str) -> str:
    pattern = r"Pick up the (.*?) and place it into the (.*?)\."
    match = re.match(pattern, task.strip())
    if not match:
        return "로봇이 물건을 정리하고 있어요."
    obj_en = match.group(1)
    target_en = match.group(2)
    obj_ko = OBJECT_KO_MAP.get(obj_en, obj_en)
    target_ko = TARGET_KO_MAP.get(target_en, target_en)
    return f"로봇이 {obj_ko}를 {target_ko}에 정리하고 있어요."


def announce_to_web_and_tts(message: str) -> None:
    web_status(message)
    play_tts(message)

@dataclass
class DatasetRecordConfig:
    # Dataset identifier. By convention it should match '{hf_username}/{dataset_name}' (e.g. `lerobot/test`).
    repo_id: str
    # A short but accurate description of the task performed during the recording (e.g. "Pick the Lego block and drop it in the box on the right.")
    single_task: str
    # Root directory where the dataset will be stored (e.g. 'dataset/path'). If None, defaults to $HF_LEROBOT_HOME/repo_id.
    root: str | Path | None = None
    # Limit the frames per second.
    fps: int = 30
    # Number of seconds for data recording for each episode.
    episode_time_s: int | float = 60
    # Number of seconds for resetting the environment after each episode.
    reset_time_s: int | float = 60
    # Number of episodes to record.
    num_episodes: int = 50
    # Encode frames in the dataset into video
    video: bool = True
    # Upload dataset to Hugging Face hub.
    push_to_hub: bool = True
    # Upload on private repository on the Hugging Face hub.
    private: bool = False
    # Add tags to your dataset on the hub.
    tags: list[str] | None = None
    # Number of subprocesses handling the saving of frames as PNG. Set to 0 to use threads only;
    # set to ≥1 to use subprocesses, each using threads to write images. The best number of processes
    # and threads depends on your system. We recommend 4 threads per camera with 0 processes.
    # If fps is unstable, adjust the thread count. If still unstable, try using 1 or more subprocesses.
    num_image_writer_processes: int = 0
    # Number of threads writing the frames as png images on disk, per camera.
    # Too many threads might cause unstable teleoperation fps due to main thread being blocked.
    # Not enough threads might cause low camera fps.
    num_image_writer_threads_per_camera: int = 4
    # Number of episodes to record before batch encoding videos
    # Set to 1 for immediate encoding (default behavior), or higher for batched encoding
    video_encoding_batch_size: int = 1
    # Video codec for encoding videos. Options: 'h264', 'hevc', 'libsvtav1', 'auto',
    # or hardware-specific: 'h264_videotoolbox', 'h264_nvenc', 'h264_vaapi', 'h264_qsv'.
    # Use 'auto' to auto-detect the best available hardware encoder.
    vcodec: str = "libsvtav1"
    # Enable streaming video encoding: encode frames in real-time during capture instead
    # of writing PNG images first. Makes save_episode() near-instant. More info in the documentation: https://huggingface.co/docs/lerobot/streaming_video_encoding
    streaming_encoding: bool = False
    # Maximum number of frames to buffer per camera when using streaming encoding.
    # ~1s buffer at 30fps. Provides backpressure if the encoder can't keep up.
    encoder_queue_maxsize: int = 30
    # Number of threads per encoder instance. None = auto (codec default).
    # Lower values reduce CPU usage, maps to 'lp' (via svtav1-params) for libsvtav1 and 'threads' for h264/hevc..
    encoder_threads: int | None = None
    # Rename map for the observation to override the image and state keys
    rename_map: dict[str, str] = field(default_factory=dict)

    def __post_init__(self):
        if self.single_task is None:
            raise ValueError("You need to provide a task as argument in `single_task`.")


@dataclass
class RecordConfig:
    robot: RobotConfig
    dataset: DatasetRecordConfig
    # Whether to control the robot with a teleoperator
    teleop: TeleoperatorConfig | None = None
    # Whether to control the robot with a policy
    policy: PreTrainedConfig | None = None
    # Display all cameras on screen
    display_data: bool = False
    # Display data on a remote Rerun server
    display_ip: str | None = None
    # Port of the remote Rerun server
    display_port: int | None = None
    # Whether to  display compressed images in Rerun
    display_compressed_images: bool = False
    # Use vocal synthesis to read events.
    play_sounds: bool = True
    # Resume recording on an existing dataset.
    resume: bool = False

    def __post_init__(self):
        # HACK: We parse again the cli args here to get the pretrained path if there was one.
        policy_path = parser.get_path_arg("policy")

        if policy_path:
            cli_overrides = parser.get_cli_overrides("policy")

            self.policy = PreTrainedConfig.from_pretrained(policy_path, cli_overrides=cli_overrides)
            self.policy.pretrained_path = policy_path

        # 웹 서버에서 모드를 직접 넘기는 경우에는 record() 내부에서 모드별 policy를 로드합니다.
        # 따라서 CLI 단계에서 teleop/policy가 없어도 허용합니다.
        allow_web_mode = os.environ.get("LEROBOT_MODE_SELECT") is not None

        if self.teleop is None and self.policy is None and not allow_web_mode:
            raise ValueError("Choose a policy, a teleoperator or both to control the robot")

    @classmethod
    def __get_path_fields__(cls) -> list[str]:
        """This enables the parser to load config from the policy using `--policy.path=local/dir`"""
        return ["policy"]


""" --------------- record_loop() data flow --------------------------
       [ Robot ]
           V
     [ robot.get_observation() ] ---> raw_obs
           V
     [ robot_observation_processor ] ---> processed_obs
           V
     .-----( ACTION LOGIC )------------------.
     V                                       V
     [ From Teleoperator ]                   [ From Policy ]
     |                                       |
     |  [teleop.get_action] -> raw_action    |   [predict_action]
     |          |                            |          |
     |          V                            |          V
     | [teleop_action_processor]             |          |
     |          |                            |          |
     '---> processed_teleop_action           '---> processed_policy_action
     |                                       |
     '-------------------------.-------------'
                               V
                  [ robot_action_processor ] --> robot_action_to_send
                               V
                    [ robot.send_action() ] -- (Robot Executes)
                               V
                    ( Save to Dataset )
                               V
                  ( Rerun Log / Loop Wait )
"""


@safe_stop_image_writer
def record_loop(
    robot: Robot,
    events: dict,
    fps: int,
    teleop_action_processor: RobotProcessorPipeline[
        tuple[RobotAction, RobotObservation], RobotAction
    ],  # runs after teleop
    robot_action_processor: RobotProcessorPipeline[
        tuple[RobotAction, RobotObservation], RobotAction
    ],  # runs before robot
    robot_observation_processor: RobotProcessorPipeline[
        RobotObservation, RobotObservation
    ],  # runs after robot
    dataset: LeRobotDataset | None = None,
    teleop: Teleoperator | list[Teleoperator] | None = None,
    policy: PreTrainedPolicy | None = None,
    preprocessor: PolicyProcessorPipeline[dict[str, Any], dict[str, Any]] | None = None,
    postprocessor: PolicyProcessorPipeline[PolicyAction, PolicyAction] | None = None,
    control_time_s: int | None = None,
    single_task: str | None = None,
    display_data: bool = False,
    display_compressed_images: bool = False,
):
    if dataset is not None and dataset.fps != fps:
        raise ValueError(f"The dataset fps should be equal to requested fps ({dataset.fps} != {fps}).")

    teleop_arm = teleop_keyboard = None
    if isinstance(teleop, list):
        teleop_keyboard = next((t for t in teleop if isinstance(t, KeyboardTeleop)), None)
        teleop_arm = next(
            (
                t
                for t in teleop
                if isinstance(
                    t,
                    (
                        so_leader.SO100Leader
                        | so_leader.SO101Leader
                        | koch_leader.KochLeader
                        | omx_leader.OmxLeader
                    ),
                )
            ),
            None,
        )

        if not (teleop_arm and teleop_keyboard and len(teleop) == 2 and robot.name == "lekiwi_client"):
            raise ValueError(
                "For multi-teleop, the list must contain exactly one KeyboardTeleop and one arm teleoperator. Currently only supported for LeKiwi robot."
            )

    # Reset policy and processor if they are provided
    if policy is not None and preprocessor is not None and postprocessor is not None:
        policy.reset()
        preprocessor.reset()
        postprocessor.reset()

    no_action_count = 0
    timestamp = 0
    start_episode_t = time.perf_counter()
    # --- [debug] realtime fps init ---
    dbg_prev_time = time.time()
    dbg_frame_count = 0
    dbg_update_interval = 2  # 10 프레임마다 한 번씩 갱신
    # ----------------------------------------------------

    while timestamp < control_time_s and not STOP_REQUESTED and not events["stop_recording"]:
        start_loop_t = time.perf_counter()

        if STOP_REQUESTED or events["exit_early"] or events["stop_recording"]:
            events["exit_early"] = False
            break

        # Get robot observation
        obs = robot.get_observation()

        if STOP_REQUESTED or events["stop_recording"]:
            break

        # Applies a pipeline to the raw robot observation, default is IdentityProcessor
        obs_processed = robot_observation_processor(obs)

        if policy is not None or dataset is not None:
            observation_frame = build_dataset_frame(dataset.features, obs_processed, prefix=OBS_STR)

        # Get action from either policy or teleop
        if policy is not None and preprocessor is not None and postprocessor is not None:
            action_values = predict_action(
                observation=observation_frame,
                policy=policy,
                device=get_safe_torch_device(policy.config.device),
                preprocessor=preprocessor,
                postprocessor=postprocessor,
                use_amp=policy.config.use_amp,
                task=single_task,
                robot_type=robot.robot_type,
            )

            act_processed_policy: RobotAction = make_robot_action(action_values, dataset.features)

        elif policy is None and isinstance(teleop, Teleoperator):
            act = teleop.get_action()

            # Applies a pipeline to the raw teleop action, default is IdentityProcessor
            act_processed_teleop = teleop_action_processor((act, obs))

        elif policy is None and isinstance(teleop, list):
            arm_action = teleop_arm.get_action()
            arm_action = {f"arm_{k}": v for k, v in arm_action.items()}
            keyboard_action = teleop_keyboard.get_action()
            base_action = robot._from_keyboard_to_base_action(keyboard_action)
            act = {**arm_action, **base_action} if len(base_action) > 0 else arm_action
            act_processed_teleop = teleop_action_processor((act, obs))
        else:
            no_action_count += 1
            if no_action_count == 1 or no_action_count % 10 == 0:
                logging.warning(
                    "No policy or teleoperator provided, skipping action generation. "
                    "This is likely to happen when resetting the environment without a teleop device. "
                    "The robot won't be at its rest position at the start of the next episode."
                )
            continue

        # Applies a pipeline to the action, default is IdentityProcessor
        if policy is not None and act_processed_policy is not None:
            action_values = act_processed_policy
            robot_action_to_send = robot_action_processor((act_processed_policy, obs))
        else:
            action_values = act_processed_teleop
            robot_action_to_send = robot_action_processor((act_processed_teleop, obs))

        if STOP_REQUESTED or events["stop_recording"]:
            break

        # Send action to robot
        # Action can eventually be clipped using `max_relative_target`,
        # so action actually sent is saved in the dataset. action = postprocessor.process(action)
        # TODO(steven, pepijn, adil): we should use a pipeline step to clip the action, so the sent action is the action that we input to the robot.
        _sent_action = robot.send_action(robot_action_to_send)

        # Write to dataset
        if dataset is not None:
            action_frame = build_dataset_frame(dataset.features, action_values, prefix=ACTION)
            frame = {**observation_frame, **action_frame, "task": single_task}
            dataset.add_frame(frame)

        if display_data:
            log_rerun_data(
                observation=obs_processed, action=action_values, compress_images=display_compressed_images
            )

        dt_s = time.perf_counter() - start_loop_t

        sleep_time_s: float = 1 / fps - dt_s
        if sleep_time_s < 0:
            print()
            logging.warning(
                f"Record loop is running slower ({1 / dt_s:.1f} Hz) than the target FPS ({fps} Hz). Dataset frames might be dropped and robot control might be unstable. Common causes are: 1) Camera FPS not keeping up 2) Policy inference taking too long 3) CPU starvation"
            )

        precise_sleep(max(sleep_time_s, 0.0))

        timestamp = time.perf_counter() - start_episode_t

        # --- [debug] realtime fps ---
        dbg_frame_count += 1
        if dbg_frame_count % dbg_update_interval == 0:
            dbg_current_time = time.time()
            elapsed = dbg_current_time - dbg_prev_time
            current_fps = dbg_update_interval / elapsed
            
            if current_fps < 25.0:
                print(f"\r⚠️ [FPS Monitor] Current FPS: {current_fps:.2f} Hz\033[K", end="", flush=True)
            else:
                print(f"\r✅ [FPS Monitor] Current FPS: {current_fps:.2f} Hz\033[K", end="", flush=True)
                
            dbg_prev_time = dbg_current_time
        # -------------------------------------------------------


@parser.wrap()
def record(cfg: RecordConfig) -> LeRobotDataset:
    global bin_weights, STOP_REQUESTED, CURRENT_EVENTS  # 🔴 추가: global선언
    STOP_REQUESTED = False
    CURRENT_EVENTS = None
    init_logging()
    logging.info(pformat(asdict(cfg)))
    if cfg.display_data:
        init_rerun(session_name="recording", ip=cfg.display_ip, port=cfg.display_port)
    display_compressed_images = (
        True
        if (cfg.display_data and cfg.display_ip is not None and cfg.display_port is not None)
        else cfg.display_compressed_images
    )

    robot = make_robot_from_config(cfg.robot)
    teleop = make_teleoperator_from_config(cfg.teleop) if cfg.teleop is not None else None

    teleop_action_processor, robot_action_processor, robot_observation_processor = make_default_processors()

    dataset_features = combine_feature_dicts(
        aggregate_pipeline_dataset_features(
            pipeline=teleop_action_processor,
            initial_features=create_initial_features(
                action=robot.action_features
            ),  # TODO(steven, pepijn): in future this should be come from teleop or policy
            use_videos=cfg.dataset.video,
        ),
        aggregate_pipeline_dataset_features(
            pipeline=robot_observation_processor,
            initial_features=create_initial_features(observation=robot.observation_features),
            use_videos=cfg.dataset.video,
        ),
    )

    dataset = None
    listener = None

    def load_policy_set(policy_path):   # 🔴 추가: Policy를 따로따로 만들어주는 함수
        policy_cfg = PreTrainedConfig.from_pretrained(
            policy_path,
            local_files_only=True,
        )
        policy_cfg.pretrained_path = policy_path

        policy_obj = make_policy(policy_cfg, ds_meta=dataset.meta)

        preprocessor_obj, postprocessor_obj = make_pre_post_processors(
            policy_cfg=policy_cfg,
            pretrained_path=policy_cfg.pretrained_path,
            dataset_stats=rename_stats(dataset.meta.stats, cfg.dataset.rename_map),
            preprocessor_overrides={
                "device_processor": {"device": policy_cfg.device},
                "rename_observations_processor": {"rename_map": cfg.dataset.rename_map},
            },
        )

        return policy_obj, preprocessor_obj, postprocessor_obj

    try:
        if cfg.resume:
            dataset = LeRobotDataset(
                cfg.dataset.repo_id,
                root=cfg.dataset.root,
                batch_encoding_size=cfg.dataset.video_encoding_batch_size,
                vcodec=cfg.dataset.vcodec,
                streaming_encoding=cfg.dataset.streaming_encoding,
                encoder_queue_maxsize=cfg.dataset.encoder_queue_maxsize,
                encoder_threads=cfg.dataset.encoder_threads,
            )

            if hasattr(robot, "cameras") and len(robot.cameras) > 0:
                dataset.start_image_writer(
                    num_processes=cfg.dataset.num_image_writer_processes,
                    num_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
                )
            sanity_check_dataset_robot_compatibility(dataset, robot, cfg.dataset.fps, dataset_features)
        else:
            # Create empty dataset or load existing saved episodes
            sanity_check_dataset_name(cfg.dataset.repo_id, cfg.policy)
            dataset = LeRobotDataset.create(
                cfg.dataset.repo_id,
                cfg.dataset.fps,
                root=cfg.dataset.root,
                robot_type=robot.name,
                features=dataset_features,
                use_videos=cfg.dataset.video,
                image_writer_processes=cfg.dataset.num_image_writer_processes,
                image_writer_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
                batch_encoding_size=cfg.dataset.video_encoding_batch_size,
                vcodec=cfg.dataset.vcodec,
                streaming_encoding=cfg.dataset.streaming_encoding,
                encoder_queue_maxsize=cfg.dataset.encoder_queue_maxsize,
                encoder_threads=cfg.dataset.encoder_threads,
            )

        # Load pretrained policy
        policy = None if cfg.policy is None else make_policy(cfg.policy, ds_meta=dataset.meta)
        preprocessor = None
        postprocessor = None
        if cfg.policy is not None:
            preprocessor, postprocessor = make_pre_post_processors(
                policy_cfg=cfg.policy,
                pretrained_path=cfg.policy.pretrained_path,
                dataset_stats=rename_stats(dataset.meta.stats, cfg.dataset.rename_map),
                preprocessor_overrides={
                    "device_processor": {"device": cfg.policy.device},
                    "rename_observations_processor": {"rename_map": cfg.dataset.rename_map},
                },
            )

        robot.connect()
        if teleop is not None:
            teleop.connect()

        listener, events = init_keyboard_listener()
        CURRENT_EVENTS = events

        if not cfg.dataset.streaming_encoding:
            logging.info(
                "Streaming encoding is disabled. If you have capable hardware, consider enabling it for way faster episode saving. --dataset.streaming_encoding=true --dataset.encoder_threads=2 # --dataset.vcodec=auto. More info in the documentation: https://huggingface.co/docs/lerobot/streaming_video_encoding"
            )

        with VideoEncodingManager(dataset):
            recorded_episodes = 0

            # 🔴 웹 전용: 웹 서버가 LEROBOT_MODE_SELECT=1/2/3 환경변수로 모드를 넘깁니다.
            # 이 파일은 input()을 기다리지 않습니다.
            mode_env = os.environ.get("LEROBOT_MODE_SELECT")

            if mode_env is None:
                raise ValueError("LEROBOT_MODE_SELECT 환경변수가 없습니다. 웹에서는 1, 2, 3 중 하나가 전달되어야 합니다.")

            try:
                mode_select = int(mode_env)
            except ValueError as exc:
                play_tts("존재하지 않는 모드입니다.")
                raise ValueError(f"Invalid LEROBOT_MODE_SELECT: {mode_env}") from exc

            if mode_select not in (1, 2, 3):
                play_tts("존재하지 않는 모드입니다.")
                raise ValueError(f"Invalid LEROBOT_MODE_SELECT: {mode_select}")

            # 🔴 추가: MODE 1
            if mode_select == 1:
                recorded_episodes = cfg.dataset.num_episodes

                policy_sets = {     #경로필요
                    0: load_policy_set(str(MODEL_POLICIES_DIR / "organize_screwdriver")),
                    1: load_policy_set(str(MODEL_POLICIES_DIR / "organize_battery")),
                    2: load_policy_set(str(MODEL_POLICIES_DIR / "organize_screwdriver")),
                    3: load_policy_set(str(MODEL_POLICIES_DIR / "organize_screwdriver")),
                }

                while not STOP_REQUESTED and not events["stop_recording"]:
                    log_say(f"Recording episode {dataset.num_episodes}", cfg.play_sounds)

                    cam = robot.cameras["top"]
                    img = cam.read()
                    rl_img_path = "rl_img_top.png"
                    Image.fromarray(img, mode="RGB").save(rl_img_path)
                    detected_objects = detect_object(rl_img_path)
                    rl_obs = detected_to_obs(detected_objects, bin_weights)
                    decision = decide_action(rl_obs)
                    if decision["success"]:
                        print("\n===== RL Decision =====")
                        print(decision["script"])
                        bin_weights = update_bin_weights(bin_weights, decision)
                        print("Updated bin weights:", bin_weights)
                    else:
                        print("정리가 완료되었으므로 종료합니다.")
                        break

                    object_id = decision["target_object_id"]
                    current_policy, current_preprocessor, current_postprocessor = policy_sets[object_id]

                    announce_to_web_and_tts(task_to_korean_cleanup_message(decision["script"]))
                    web_running()
                    record_loop(
                        robot=robot,
                        events=events,
                        fps=cfg.dataset.fps,
                        teleop_action_processor=teleop_action_processor,
                        robot_action_processor=robot_action_processor,
                        robot_observation_processor=robot_observation_processor,
                        teleop=teleop,
                        policy=current_policy,
                        preprocessor=current_preprocessor,
                        postprocessor=current_postprocessor,
                        dataset=dataset,
                        control_time_s=cfg.dataset.episode_time_s,
                        single_task=decision["script"],
                        display_data=cfg.display_data,
                        display_compressed_images=display_compressed_images,
                    )

                    if STOP_REQUESTED or events["stop_recording"]:
                        dataset.clear_episode_buffer()
                        break

                    dataset.save_episode()
                    recorded_episodes += 1

                if not STOP_REQUESTED:
                    announce_to_web_and_tts("정리모드를 다 했어요.")

            # 🔴 추가: MODE 2
            elif mode_select == 2:
                print("Selected Mode : Packing Mode")

                POLICY_PATH_MODE2 = str(MODEL_POLICIES_DIR / "packing_mode")      #경로필요
                policy_mode2, pre_mode2, post_mode2 = load_policy_set(POLICY_PATH_MODE2)

                while recorded_episodes < cfg.dataset.num_episodes and not STOP_REQUESTED and not events["stop_recording"]:
                    log_say(f"Recording episode {dataset.num_episodes}", cfg.play_sounds)
                    announce_to_web_and_tts("로봇이 드라이버랑 배터리를 공구상자에 넣고 있어요.")
                    web_running()
                    record_loop(
                        robot=robot,
                        events=events,
                        fps=cfg.dataset.fps,
                        teleop_action_processor=teleop_action_processor,
                        robot_action_processor=robot_action_processor,
                        robot_observation_processor=robot_observation_processor,
                        teleop=teleop,
                        policy=policy_mode2,
                        preprocessor=pre_mode2,
                        postprocessor=post_mode2,
                        dataset=dataset,
                        control_time_s=cfg.dataset.episode_time_s,
                        single_task="Place box and put all objects into box.",    # task 입력
                        display_data=cfg.display_data,
                        display_compressed_images=display_compressed_images,
                    )

                    # Execute a few seconds without recording to give time to manually reset the environment
                    # Skip reset for the last episode to be recorded
                    if not STOP_REQUESTED and not events["stop_recording"] and (
                        (recorded_episodes < cfg.dataset.num_episodes - 1) or events["rerecord_episode"]
                    ):
                        log_say("Reset the environment", cfg.play_sounds)

                        # reset g1 robot
                        if robot.name == "unitree_g1":
                            robot.reset()

                        record_loop(
                            robot=robot,
                            events=events,
                            fps=cfg.dataset.fps,
                            teleop_action_processor=teleop_action_processor,
                            robot_action_processor=robot_action_processor,
                            robot_observation_processor=robot_observation_processor,
                            teleop=teleop,
                            control_time_s=cfg.dataset.reset_time_s,
                            single_task=cfg.dataset.single_task,
                            display_data=cfg.display_data,
                        )

                    if events["rerecord_episode"]:
                        log_say("Re-record episode", cfg.play_sounds)
                        events["rerecord_episode"] = False
                        events["exit_early"] = False
                        dataset.clear_episode_buffer()
                        continue

                    if STOP_REQUESTED or events["stop_recording"]:
                        dataset.clear_episode_buffer()
                        break

                    dataset.save_episode()
                    announce_to_web_and_tts("패킹모드를 다 했어요.")
                    recorded_episodes += 1

            # 🔴 추가: MODE 3
            elif mode_select == 3:
                print("Selected Mode : Setting Mode")

                POLICY_PATH_MODE3_1 = str(MODEL_POLICIES_DIR / "setting_mode_1st")      #경로필요
                POLICY_PATH_MODE3_2 = str(MODEL_POLICIES_DIR / "setting_mode_2nd")      #경로필요
                policy_mode3_1, pre_mode3_1, post_mode3_1 = load_policy_set(POLICY_PATH_MODE3_1)
                policy_mode3_2, pre_mode3_2, post_mode3_2 = load_policy_set(POLICY_PATH_MODE3_2)

                while recorded_episodes < cfg.dataset.num_episodes and not STOP_REQUESTED and not events["stop_recording"]:
                    log_say(f"Recording episode {dataset.num_episodes}", cfg.play_sounds)
                    announce_to_web_and_tts("로봇이 드라이버를 세팅하고 있어요.")
                    web_running()
                    record_loop(
                        robot=robot,
                        events=events,
                        fps=cfg.dataset.fps,
                        teleop_action_processor=teleop_action_processor,
                        robot_action_processor=robot_action_processor,
                        robot_observation_processor=robot_observation_processor,
                        teleop=teleop,
                        policy=policy_mode3_1,
                        preprocessor=pre_mode3_1,
                        postprocessor=post_mode3_1,
                        dataset=dataset,
                        control_time_s=25,
                        single_task="Place the screwdriver.",    # task입력
                        display_data=cfg.display_data,
                        display_compressed_images=display_compressed_images,
                    )

                    if not STOP_REQUESTED and not events["stop_recording"]:
                        announce_to_web_and_tts("로봇이 컵이랑 배터리를 세팅하고 있어요.")
                        web_running()
                        record_loop(
                            robot=robot,
                            events=events,
                            fps=cfg.dataset.fps,
                            teleop_action_processor=teleop_action_processor,
                            robot_action_processor=robot_action_processor,
                            robot_observation_processor=robot_observation_processor,
                            teleop=teleop,
                            policy=policy_mode3_2,
                            preprocessor=pre_mode3_2,
                            postprocessor=post_mode3_2,
                            dataset=dataset,
                            control_time_s=50,
                            single_task="Place objects to specific location",    # task입력
                            display_data=cfg.display_data,
                            display_compressed_images=display_compressed_images,
                        )

                    # Execute a few seconds without recording to give time to manually reset the environment
                    # Skip reset for the last episode to be recorded
                    if not STOP_REQUESTED and not events["stop_recording"] and (
                        (recorded_episodes < cfg.dataset.num_episodes - 1) or events["rerecord_episode"]
                    ):
                        log_say("Reset the environment", cfg.play_sounds)

                        # reset g1 robot
                        if robot.name == "unitree_g1":
                            robot.reset()

                        record_loop(
                            robot=robot,
                            events=events,
                            fps=cfg.dataset.fps,
                            teleop_action_processor=teleop_action_processor,
                            robot_action_processor=robot_action_processor,
                            robot_observation_processor=robot_observation_processor,
                            teleop=teleop,
                            control_time_s=cfg.dataset.reset_time_s,
                            single_task=cfg.dataset.single_task,
                            display_data=cfg.display_data,
                        )

                    if events["rerecord_episode"]:
                        log_say("Re-record episode", cfg.play_sounds)
                        events["rerecord_episode"] = False
                        events["exit_early"] = False
                        dataset.clear_episode_buffer()
                        continue

                    if STOP_REQUESTED or events["stop_recording"]:
                        dataset.clear_episode_buffer()
                        break

                    dataset.save_episode()
                    announce_to_web_and_tts("세팅모드를 다 했어요.")
                    recorded_episodes += 1
            
            # 🔴 추가: 없는 모드 선택
            else:
                play_tts("존재하지 않는 모드입니다.")
            
    finally:
        CURRENT_EVENTS = None
        log_say("Stop recording", cfg.play_sounds, blocking=True)

        if dataset:
            dataset.finalize()

        if robot.is_connected:
            robot.disconnect()
        if teleop and teleop.is_connected:
            teleop.disconnect()

        if not is_headless() and listener:
            listener.stop()

        if cfg.dataset.push_to_hub:
            dataset.push_to_hub(tags=cfg.dataset.tags, private=cfg.dataset.private)

        log_say("Exiting", cfg.play_sounds)
    return dataset


def main():
    register_third_party_plugins()
    record()


if __name__ == "__main__":
    main()
